server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    max-http-form-post-size: 100MB
  error:
    include-exception: true

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  output:
    ansi:
      enabled: always

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  banner:
    location: classpath:banner.txt


logging:
  config: classpath:logging.xml
#  file:
#    name: log日志/文件服务器日志.log

