server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
  tomcat:
    max-http-form-post-size: 100MB

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  banner:
    image:
      location: classpath:/static/img/123.png
      pixelmode: text
    location: classpath:banner.txt

logging:
  file:
    name: log日志/文件服务器日志.log
  pattern:
    rolling-file-name: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz


